# 1. Create Numpy Arrays: total 26 points

1). Convert a Python list x=[[1,2,3],[4,5,6]] into a Numpy array.                                          1 point

In [1]:
x = [[1,2,3],[4,5,6]]

In [2]:
import numpy as np
from sys import getsizeof

In [3]:
numpy_arr = np.array(x)
numpy_arr

array([[1, 2, 3],
       [4, 5, 6]])

2). Use one line to create a 3x2 2D array with shape of (3,2), filled with 1-6.                    1 point

In [4]:
a = np.arange(1,7).reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

3). Create an array of 2, 4, 6, 8, ..., 98, 100; and find the mean value.                                 1 point

In [5]:
b = np.arange(2,101,2)
print(b)
mean = np.mean(b)
print("The mean of the numpy array b is: {}".format(mean))

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
The mean of the numpy array b is: 51.0


4). Create an 3x3x3 array filled with arbitrary values; and find the minimum and maximum values.  1 point

In [6]:
c = np.random.random((3,3,3))
print("The 3x3x3 array with arbitrary values is:")
print(c)
minimum = c.min()
maximum = c.max()
print('Minimum of numpy array c is: {}'.format(minimum))
print('Maximum of numpy array c is: {}'.format(maximum))


The 3x3x3 array with arbitrary values is:
[[[0.01186278 0.5705031  0.07000282]
  [0.83564771 0.68244941 0.9838852 ]
  [0.93732603 0.7845685  0.70917074]]

 [[0.94236603 0.57650826 0.09539101]
  [0.42238834 0.58822348 0.80616548]
  [0.02273496 0.61034459 0.21794224]]

 [[0.47276658 0.31631917 0.63784974]
  [0.14949229 0.96421597 0.1485345 ]
  [0.00504041 0.65660042 0.54496399]]]
Minimum of numpy array c is: 0.00504041220717899
Maximum of numpy array c is: 0.9838852006351239


5). Create a random array of size 10 and sort it.                                                                     1 point

In [7]:
d = np.random.random(10)
print("The random array of size of 10 is:")
print(d)
d.sort()
print("")
print("The sorted array is:")
print(d)

The random array of size of 10 is:
[0.26811391 0.72503551 0.97132395 0.4384801  0.47254198 0.88781322
 0.27697511 0.38312017 0.35158785 0.8347691 ]

The sorted array is:
[0.26811391 0.27697511 0.35158785 0.38312017 0.4384801  0.47254198
 0.72503551 0.8347691  0.88781322 0.97132395]


6). Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers.             1 point

In [8]:
e = np.arange(5,35,3)
e

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

7). Create an arbitrary array of shape (10,10); and find the memory size of this array.       1 points

In [9]:
f = np.random.random((10,10))
print("The random array of size 100 and shape of 10x10 is:")
print(f)
print("Memory size of the array f bytes", f.nbytes)
size_arr = f.size
one_ele_size = f.itemsize
print(" ")
print("The memory size of the numpy array f is: {} bytes".format(size_arr * one_ele_size))
print("The size of the array f as whole object is: {} bytes".format(getsizeof(f)))

The random array of size 100 and shape of 10x10 is:
[[0.2845975  0.21583136 0.55538478 0.24385613 0.45703289 0.56005133
  0.00617091 0.00983304 0.1447524  0.42904359]
 [0.66066539 0.88896617 0.85819769 0.72168347 0.41485717 0.32004583
  0.46426518 0.73930865 0.86477692 0.39145625]
 [0.91269632 0.80816455 0.84476657 0.28807412 0.57800304 0.27378299
  0.84133072 0.13610557 0.54324519 0.35175219]
 [0.10622245 0.54988598 0.31289136 0.57197676 0.55147562 0.29868864
  0.5013601  0.21378541 0.44473534 0.13679478]
 [0.62952904 0.85717661 0.26781841 0.96268808 0.82463499 0.32578492
  0.45182008 0.53370488 0.36079627 0.83272113]
 [0.9212638  0.85262293 0.71399179 0.45961655 0.25465444 0.02095375
  0.59535513 0.0467704  0.671872   0.76726298]
 [0.70431913 0.62101152 0.45283748 0.47293177 0.82473581 0.51203568
  0.01479182 0.05494898 0.90540507 0.97250916]
 [0.42410559 0.76646649 0.21787957 0.71379765 0.34966924 0.42909478
  0.49493473 0.48353579 0.80224417 0.29945721]
 [0.59941292 0.86580279 0.30

8). Create a null array of size 10 but the fifth value which is 1.                                             1 points

In [10]:
g = np.zeros(10)
g[4] = 1
g


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

9). Create an array with values ranging from 10 to 49; and reverse it then (first element becomes last).                   1 point

In [11]:
h = np.arange(10,49)
print("The array with the values ranging from 10 to 49 are:")
print(h)
print("")
rev = np.flip(h)
print("The reverse of the array is:")
print(rev)

The array with the values ranging from 10 to 49 are:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]

The reverse of the array is:
[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


10). Create an array of shape (3, 2) with random values from a uniform distribution over [0, 1) and confirm you can get the same value when you run it next time.                    1 point

In [12]:
np.random.seed(0)
i = np.random.random(6).reshape(3,2)
# random.random returns an array with the uniform distribution values ranging from including 0 but excluding 1.
i

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411]])

11). Create a 5x5 matrix with row values ranging from 0 to 4:                                  2 points

In [13]:
j = np.zeros((5,5), dtype = int)
j = j + np.arange(5)
j

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

12). Add a border (filled with 0's) around an existing array:                                     4 points

In [14]:
k = np.ones((5,5))
k = np.pad(k, pad_width = 1, mode = 'constant', constant_values = 0)
k

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

13). Create a 5x5 2D array with values 1,2,3,4,5 on the diagonal.                  4 points

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
 
 Then, make 1,2,3,4 move below the diagonal:
 
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]

In [15]:
l = np.diag([1,2,3,4,5])
print(l)

print("")

l = np.diag(1+np.arange(4), k = -1)
print(l)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


14). Create a 2d 10x10 array with 1 on the border and 0 inside.                  4 points

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

In [16]:
m = np.zeros((9,9))
m = np.pad(m, pad_width = 1, mode = 'constant', constant_values = 1)
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

15). Extract the integer part of a random array of positive numbers using 2 different methods, and the result should be an integer array.                2 points

In [17]:
n = np.random.uniform(0,10,10)
print(n)
print(n-n%1)
print(np.floor(n))
print(np.trunc(n))
a = np.array((np.trunc(n)), dtype =int)
a
# make integer array

[4.37587211 8.91773001 9.63662761 3.83441519 7.91725038 5.2889492
 5.68044561 9.25596638 0.71036058 0.871293  ]
[4. 8. 9. 3. 7. 5. 5. 9. 0. 0.]
[4. 8. 9. 3. 7. 5. 5. 9. 0. 0.]
[4. 8. 9. 3. 7. 5. 5. 9. 0. 0.]


array([4, 8, 9, 3, 7, 5, 5, 9, 0, 0])

# 2. Operations on Numpy Arrays: total 38 points

1). Find the index of 5th repetition of number 1 in the given array x.  x: [1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2]        2 points

In [19]:
x = [1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2]
# assuming that  first occurence of 1 is not the repetition. Therefore the 6th occurence of 1 is being considered as the 5th repetition. 
ind = 0
count = 0
while count <= 5:
    if x[ind] == 1:
        count += 1
        if count == 5:
            break
    else:
        pass
    ind += 1
print('The index value of 5th repetition of 1 is: {}'.format(ind))


    

The index value of 5th repetition of 1 is: 8


2). Use arange to get an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.                                           2 points

In [20]:
o = np.arange(1,10)
print("The array with the range of values from 1 to 9 is: ",o)
print("")
split_arr = np.split(o,[4,6])
print(split_arr)

The array with the range of values from 1 to 9 is:  [1 2 3 4 5 6 7 8 9]

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


3). Use arange to generate the following 2D array:  [[ 0., 1., 2., 3.],
 [ 4., 5., 6., 7.],
 [ 8., 9., 10., 11.],
 [ 12., 13., 14., 15.]]             2 points

In [21]:
p = np.arange(16).reshape(4,4)
p

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Use np.split to split the array into left and right halves.

In [22]:
q = np.hsplit(p,2)
q

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

4). Given an 2D array:       [[5,10,15],
 [20,25,30],
 [35,40,45]]                                          2 points

In [23]:
x = np.array([5,10,15,20,25,30,35,40,45]).reshape(3,3)
x



array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

(1) Slicing to get the sub-array [[10,15], [25,30]]

In [24]:
x[0:2,1:]

array([[10, 15],
       [25, 30]])

(2) Getting individual element value "20"

In [25]:
y = np.where(x == 20)
print(y)
print(x[y])

# or 
x[1,0]

(array([1], dtype=int64), array([0], dtype=int64))
[20]


20

5). Let x be an array:                        [[ 1 2 3],
 [ 4 5 6]] and y be an array [[ 7 8 9],
 [10 11 12]]                           2 points

Concatenate x and y so that a new array looks like [[1, 2, 3, 7, 8, 9],
 [4, 5, 6, 10, 11, 12]]

In [26]:
x = np.array([1,2,3,4,5,6]).reshape(2,3)
y = np.array([7,8,9,10,11,12]).reshape(2,3)
print("The concatenated array x & y is:")
np.concatenate([x,y],axis = 1)

The concatenated array x & y is:


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

6). Compute the min/max (min is divided by max) on each row for a given 2d array, in which integer values range from 1 to 10 [1,10) and shape is (5,3).             2 points

Here requires a random seed to keep the same value from the random generator.

In [27]:
np.random.seed(0) # using seed for reproducing the same numbers when using random.randint method for creation of array
x = np.random.randint(1,10,size = (5,3))
print("The random reproducible array in the range of 10 and shape of 5 rows and 3 columns is as forllows : {}".format(x))
max_element = np.amax(x,axis = 1).reshape(5,1) # max values of each row
print("The maximum values in each row of the array are: {}".format(max_element))

min_element = np.amin(x,axis = 1).reshape(5,1) # min values of each row
print("The minimum values in each row of the array are: {}".format(min_element))

ratio = min_element/max_element
print("The min/max ratio of the values in each row of the array are: {}".format(ratio))

The random reproducible array in the range of 10 and shape of 5 rows and 3 columns is as forllows : [[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]
 [9 2 7]]
The maximum values in each row of the array are: [[6]
 [8]
 [6]
 [9]
 [9]]
The minimum values in each row of the array are: [[1]
 [4]
 [3]
 [7]
 [2]]
The min/max ratio of the values in each row of the array are: [[0.16666667]
 [0.5       ]
 [0.5       ]
 [0.77777778]
 [0.22222222]]


7). Normalize a 5x5 random matrix:                          2 points

Tips: a normalization operates like: (the array - the mean)/the standard deviation

In [28]:
np.random.seed(0)
x = np.random.random((5,5))
print("The original array is: ")
print(x)
x_min = x.min()
x_max = x.max()

print(" ")
print("After normalization, the array is: ")
print((x - x_min)/(x_max - x_min))

The original array is: 
[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]]
 
After normalization, the array is: 
[[0.55153917 0.7251367  0.60783077 0.54743825 0.42094786]
 [0.65283363 0.43548501 0.90938507 0.98439526 0.37898909]
 [0.80499445 0.530756   0.57160496 0.94467685 0.05302344]
 [0.06981522 0.         0.84766433 0.79083723 0.88667967]
 [1.         0.81275064 0.46041422 0.79331263 0.10231222]]


8). Convert 3 arrays into a 1d array.                          2 points

arr1: 0,1,2

arr2: 3,4,5,6

arr3: 7,8,9

Generate the 3 arrays by numpy arange()

Desired Output:

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr1 = np.arange(3)
print(arr1)
arr2 = np.arange(3,7)
print(arr2)
arr3 = np.arange(7,10)
print(arr3)

[0 1 2]
[3 4 5 6]
[7 8 9]


In [30]:
np.concatenate([arr1,arr2,arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

9). Get all items between 15 and 55 from aa, math expression: [15,55].                  2 points

The aa is uniformly distributed integers in a 1D array (size=20) with given values (<100). Requires defining a seed.

In [31]:
np.random.seed(0)
aa = np.random.randint(100, size = 20)
aa

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39,
       87, 46, 88])

In [32]:
result = aa[(aa >= 15) & (aa <= 55)]
result

array([44, 47, 21, 36, 39, 46])

10). Get the positions where elements of a and b match.                 2 points

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

In [33]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
positions = np.where(np.in1d(a,b))
print("The intersection postions between arrays a & b are : {}".format(positions))


The intersection postions between arrays a & b are : (array([1, 3, 5, 7], dtype=int64),)


11). Use arange() to create an array from 0 to 20 ( [0,20) ); replace all odd numbers with -1.      2 points

In [34]:
z = np.arange(20)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
print("Replacing all the odd numbers with -1")
z[z%2==1] = -1
z

Replacing all the odd numbers with -1


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1])

12). Use two addition functions of Numpy to add every element in a 1D array of size 10 and finally get one value.; and set a timer to time the two addition functions to see which one is faster.                                2 points

Tips: you can use Jupyter magic command %timeit

In [36]:
x = np.arange(10)
print(x)
tot_sum = sum(x)
%timeit tot_sum = sum(x)
print(tot_sum)
total = np.sum(x)
%timeit total = np.sum(x)
print(total)
tot_value = np.cumsum(x)[-1]
%timeit tot_value = np.cumsum(x)[-1]
print(tot_value)
print("As per the operations using three methods the 'sum()', 'np.sum()' & 'cumsum()' methods to add the values of the array, the 'sum()' method is faster.")

[0 1 2 3 4 5 6 7 8 9]
2.17 µs ± 701 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
45
5.17 µs ± 969 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
45
3.15 µs ± 483 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
45
As per the operations using three methods the 'sum()', 'np.sum()' & 'cumsum()' methods to add the values of the array, the 'sum()' method is faster.


13). Subtract the mean of each row of a matrix X. X is a random 2D 5x10 array.     2 points

In [37]:
np.random.seed(0)
X = np.random.randint(50,size = (5,10))
print(X)
X_mean = X.mean(axis = 1, keepdims = True)
print(X_mean.reshape(5,1))
Y = X - X_mean
Y


[[44 47  0  3  3 39  9 19 21 36]
 [23  6 24 24 12  1 38 39 23 46]
 [24 17 37 25 13  8  9 20 16  5]
 [15 47  0 18 35 24 49 29 19 19]
 [14 39 32  1  9 32 31 10 23 35]]
[[22.1]
 [23.6]
 [17.4]
 [25.5]
 [22.6]]


array([[ 21.9,  24.9, -22.1, -19.1, -19.1,  16.9, -13.1,  -3.1,  -1.1,
         13.9],
       [ -0.6, -17.6,   0.4,   0.4, -11.6, -22.6,  14.4,  15.4,  -0.6,
         22.4],
       [  6.6,  -0.4,  19.6,   7.6,  -4.4,  -9.4,  -8.4,   2.6,  -1.4,
        -12.4],
       [-10.5,  21.5, -25.5,  -7.5,   9.5,  -1.5,  23.5,   3.5,  -6.5,
         -6.5],
       [ -8.6,  16.4,   9.4, -21.6, -13.6,   9.4,   8.4, -12.6,   0.4,
         12.4]])

14) Considering a four dimensions array (3,4,3,4) with the values 0-9 randomly, how to get sum over the last two axis at once?                    6 points

In [38]:
np.random.seed(0)
x = np.random.randint(10,size = (3,4,3,4))
x

array([[[[5, 0, 3, 3],
         [7, 9, 3, 5],
         [2, 4, 7, 6]],

        [[8, 8, 1, 6],
         [7, 7, 8, 1],
         [5, 9, 8, 9]],

        [[4, 3, 0, 3],
         [5, 0, 2, 3],
         [8, 1, 3, 3]],

        [[3, 7, 0, 1],
         [9, 9, 0, 4],
         [7, 3, 2, 7]]],


       [[[2, 0, 0, 4],
         [5, 5, 6, 8],
         [4, 1, 4, 9]],

        [[8, 1, 1, 7],
         [9, 9, 3, 6],
         [7, 2, 0, 3]],

        [[5, 9, 4, 4],
         [6, 4, 4, 3],
         [4, 4, 8, 4]],

        [[3, 7, 5, 5],
         [0, 1, 5, 9],
         [3, 0, 5, 0]]],


       [[[1, 2, 4, 2],
         [0, 3, 2, 0],
         [7, 5, 9, 0]],

        [[2, 7, 2, 9],
         [2, 3, 3, 2],
         [3, 4, 1, 2]],

        [[9, 1, 4, 6],
         [8, 2, 3, 0],
         [0, 6, 0, 6]],

        [[3, 3, 8, 8],
         [8, 2, 3, 2],
         [0, 8, 8, 3]]]])

In [39]:
x.sum(axis= 2)

array([[[14, 13, 13, 14],
        [20, 24, 17, 16],
        [17,  4,  5,  9],
        [19, 19,  2, 12]],

       [[11,  6, 10, 21],
        [24, 12,  4, 16],
        [15, 17, 16, 11],
        [ 6,  8, 15, 14]],

       [[ 8, 10, 15,  2],
        [ 7, 14,  6, 13],
        [17,  9,  7, 12],
        [11, 13, 19, 13]]])

In [40]:
x.sum(axis=3)

array([[[11, 24, 19],
        [23, 23, 31],
        [10, 10, 15],
        [11, 22, 19]],

       [[ 6, 24, 18],
        [17, 27, 12],
        [22, 17, 20],
        [20, 15,  8]],

       [[ 9,  5, 21],
        [20, 10, 10],
        [20, 13, 12],
        [22, 15, 19]]])

In [41]:
np.apply_over_axes(np.sum, x, [2,3])

array([[[[54]],

        [[77]],

        [[35]],

        [[52]]],


       [[[48]],

        [[56]],

        [[59]],

        [[43]]],


       [[[35]],

        [[40]],

        [[45]],

        [[56]]]])

In [42]:
x.sum(axis=(2,3))

array([[54, 77, 35, 52],
       [48, 56, 59, 43],
       [35, 40, 45, 56]])

15). Use np.put to randomly place 3 numbers (which can be any value, like 5) in a 2D 10x10 zero array:             6 points

Tips: here, randomly placing 3 numbers means you should first randomly generate the indexes of the 3 numbers in the 2D 10x10 array.

In [44]:
a = np.zeros(100).reshape(10,10)
m = a.shape[0]
print(m)
np.put(a, np.random.choice(range(m*m), 3, replace = False),5)
print("The array with three values of 5 in random positions is: ")
a

10
The array with three values of 5 in random positions is: 


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 5., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 5.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# 3. Indexing and Slicing: total 14 points

1) Given a 1d array: [ 3, 6, 9, 25, 10, 8]                      4 points

(1) To get all elements except the first:

(2) To get all elements except the last:

(3) To get every other element of the array (operation from the first element):

(4) To reverse the array:

In [45]:
a = np.array([3,6,9,25,10,8])
print("To get all elements except the first: ",a[1:])
print("To get all elements except the last: ",a[:len(a)-1])
print("To get every other element of the array (operation from the first element): ",a[::2])
print("To reverse the array: ", np.flip(a))

To get all elements except the first:  [ 6  9 25 10  8]
To get all elements except the last:  [ 3  6  9 25 10]
To get every other element of the array (operation from the first element):  [ 3  9 10]
To reverse the array:  [ 8 10 25  9  6  3]


2) Multidimensional Arrays:               4 points

(1) create an array with the components as 0-31 and the shape is (8,4).

(2) set the 3rd element in the 1st row to 0.

(3) print out the second column.

(4) Get the 3x3 region from the array:

([ 9, 10, 11],

 [13, 14, 15],

 [17, 18, 19]])

In [46]:
x = np.arange(32).reshape(8,4)
print("An array with the components as 0-31 and the shape is (8,4):")
x

An array with the components as 0-31 and the shape is (8,4):


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [47]:
print("Set the 3rd element in the 1st row to 0")
x[0,2] = 0
x

Set the 3rd element in the 1st row to 0


array([[ 0,  1,  0,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [48]:
print("Print out the second column")
x[0:,1:2]

Print out the second column


array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21],
       [25],
       [29]])

In [49]:
print("Get the 3x3 region from the array")
x[2:5,1:]

Get the 3x3 region from the array


array([[ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

3) Create an 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal. Please use the numpy "slicing" method to realize.                4 points

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]

In [50]:
x = np.zeros(16).reshape(4,4)
x[::2,1::2] = 1
x[1::2,::2] = 1
x

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

4) Swap the first two rows of the array: aa = np.arange(20).reshape(5,4)                2 points

In [51]:
aa = np.arange(20).reshape(5,4)
aa

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [52]:
print("Swapping the first two rows of the array:")
aa[[0,1]] = aa[[1,0]]
aa

Swapping the first two rows of the array:


array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# 4. Broadcasting in Practice: total 22 points

1) Use rules of broadcasting to give steps how adding two arrays:                          6 points

M = np.ones((3, 2))

a = np.arange(3)

Using Rule 1:

Using Rule 2:

Giving the result or Using Rule 3:

In [53]:
M = np.ones((3,2), dtype = int)
print(M)
print("The shape of M is: ",M[:, np.newaxis].shape)
a = np.arange(3)
print(a)
print("The shape of a is: ",a[:, np.newaxis].shape)
M+a # this will throw an error as the dimensions of the two array's 'M' & 'a' are not compatible to do the addition.

[[1 1]
 [1 1]
 [1 1]]
The shape of M is:  (3, 1, 2)
[0 1 2]
The shape of a is:  (3, 1)


ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

Rules of Broadcasting for two arrays are:

Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

Rule 3:  If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [54]:
a = a[:, np.newaxis]
print(a)
print("The shape of a is: ",a[:, np.newaxis].shape)
# we introduce padding to reshape the axis of the array 'a' with less dimensions
M+a 

[[0]
 [1]
 [2]]
The shape of a is:  (3, 1, 1)


array([[1, 1],
       [2, 2],
       [3, 3]])

2) Given 2 arrays: 4 points

a_2d : [[3,3,3],
       [4,4,4],
       [5,5,5]]

b_1d : [1,2,3]

Do the subtraction so that the result is:

[[2 2 2]
 [2 2 2]
 [2 2 2]]

In [55]:
a_2d = np.array([3,3,3,4,4,4,5,5,5]).reshape(3,3)
print(a_2d)
print("")

b_1d = np.arange(1,4)
print(b_1d)

[[3 3 3]
 [4 4 4]
 [5 5 5]]

[1 2 3]


In [56]:
# changing the shape of b_1d from (1 row, 3 columns) to (3 rows, 1 column)
b_1d = b_1d.reshape(3,1)
b_1d
result = a_2d - b_1d

In [57]:
result

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

3). Write a 6x6 matrix for multiplication table:          8 points

- by using numpy broadcasting (4 points)

- by using Python nested for-loop (4 points).

Desired output:

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

In [58]:
a = np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

In [59]:
b = np.arange(1,7).reshape(6,1)
b


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [60]:
c = b*a
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

In [61]:
res = []
for i in range(len(a)):
    temp = []
    for j in range(len(b)):
        #print(res[i])
        temp.append(int(a[i]*b[j]))
    res.append(temp)
np.asarray(res)


array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

4) For an arbitrary array of dimension (5,5,3), consider multiplying it by an arbitrary array with dimensions (5,5).                4 points

In [62]:
x = np.random.randint(10,size = (5,5,3))
#X = np.random.randint(50,size = (5,10))
y = np.random.randint(10, size=(5,5))
print(x*y[:,:,None])




[[[ 0  0  0]
  [27  6 15]
  [ 2  3  5]
  [28  8 28]
  [ 4 24 20]]

 [[ 0  0 12]
  [ 0  0  0]
  [ 0  0  0]
  [64 64 56]
  [ 0 32 24]]

 [[48 54 48]
  [27 54  9]
  [21 12 27]
  [ 6  0 24]
  [ 4 14 16]]

 [[ 4  4  1]
  [14 12 18]
  [ 4  1  5]
  [27 21  3]
  [12 20 28]]

 [[ 3  6  6]
  [ 7  9  1]
  [ 0  0  0]
  [21 56 28]
  [ 8 32 40]]]
